Add files via upload
DebbyBud/module1 pull request #1
Opened 2022-08-17 06:14 UTC by DebbyBud

2022-08-17 06:55 UTC, muneebulrehman reviewed
Hi @DebbyBud , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a PR with no proper title and no description.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-08-17 08:30 UTC, prolajumokeoni requested changes
Hi @DebbyBud, 
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ No linter errors
✔️ Git flow was correctly used
✔️  Good PR title and Description



## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-17 08:30 UTC, prolajumokeoni commented on test.md
> +This file should be ignored by git
- [ ] Kindly make sure your test.md file is ignored by git, currently, this is not ignored by git, please fix this as this is part of the requirements 👍🏿

2022-08-17 08:30 UTC, prolajumokeoni commented on .gitignore
> +test.md
- [ ] Kindly make sure that your .gitignore file lists node_modules directory (as it can be added by accident while setting up Linters).

2022-08-17 08:30 UTC, prolajumokeoni commented on styles.css
> +}
- [ ] Kindly link your styles.css file to the index.html file so your color can be added 👍🏿

2022-08-17 09:03 UTC, DebbyBud commented on test.md
> +This file should be ignored by git
thank you

2022-08-17 10:16 UTC, DebbyBud commented on styles.css
> +}
could you please check if the changes are there, I cnt find away to see it on github

2022-08-17 12:17 UTC, sja-thedude requested changes
## Required Changes ♻️

Hi @DebbyBud, This is @sja-thedude your code reviewer.

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![200w](https://user-images.githubusercontent.com/70269507/159484303-3187dacc-4a82-4263-bb1a-8d72417ce1d9.gif)

 ## Highlights
✔️ Good job so far

 ## Required Changes ♻️
- [ ] Kindly make the changes asked by the previous reviewer as given below:
1- First required change [here](https://github.com/DebbyBud/module1/pull/1#discussion_r947605158)
2- Second required change [here](https://github.com/DebbyBud/module1/pull/1#discussion_r947596067)
3- Third required change [here](https://github.com/DebbyBud/module1/pull/1#discussion_r947591370)

Make sure to make the changes and then push the changes to github, If you have any issues then you can contact me on slack SJA

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-18 06:08 UTC, mgmediaweb approved these changes
Hi @DebbyBud , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 💯 

- Good job following the advice of the other reviewers. ✔️

## Optional suggestions

- Kindly, the titles and description of the PR should be more descriptive about the project carried out.
- The title of your HTML must be related to your project, for example, "Hello Microverse"

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-18 06:11 UTC, merged